### PR TITLE
Implement bounding boxes for random choice

### PR DESCRIPTION
**Pull request by AmedeoBiolatti**
# What does this PR do?

Implement bound boxes augmentation for RandomChioce (https://github.com/keras-team/keras-cv/issues/729)

Only test and demo where needed, since the implementation already handled everything

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [x] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?

@LukeWood

### CODE REVIEW

**Review by LukeWood — APPROVED** [review]

**Comment by LukeWood** [comment]
Thanks for the PR!  The unit test is a good value add, so happy to merge.

I don't think the demo showcases any new features - bounding boxes "just work" with RandomChoice.

**Comment by AmedeoBiolatti** [comment]
> Thanks for the PR! The unit test is a good value add, so happy to merge.
> 
> I don't think the demo showcases any new features - bounding boxes "just work" with RandomChoice.

Should we remove the demo?

**Comment by LukeWood** [comment]
> > Thanks for the PR! The unit test is a good value add, so happy to merge.
> > I don't think the demo showcases any new features - bounding boxes "just work" with RandomChoice.
> 
> Should we remove the demo?

yeah lets remove it.

**Pull request merged**
