### PR TITLE
Add a note about mixed precision to SD `inpaint`

### LINKED ISSUE #1019: BUG: StableDiffusion.inpaint() throws float tensor error
I am using today's version (15Nov2022) of https://github.com/keras-team/keras-cv/ and I receive the following error when using `StableDiffusion.inpaint()`:

`InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a half tensor but is a float tensor [Op:AddV2]`

Is anyone also receiving this error when running `StableDiffusion.inpaint()`?

Here is my code:

```python
from tensorflow import keras
from keras_cv.models import StableDiffusion

keras.mixed_precision.set_global_policy("mixed_float16")

model = StableDiffusion(
    img_height=512, 
    img_width=512, 
    jit_compile=True
)

prompt = "photo of coffee beans"
seed = 52983

# NOTE: img1 was successfully generated using StableDiffusion.text_to_image() with the same prompt and seed values as shown above.
type(img.1) # numpy.ndarray (dtype=int8)
img1.shape # (1, 512, 512, 3)

type(mask) # numpy.ndarray (dtype=int8)
mask.shape # (1, 512, 512)

img2 = model.inpaint(
        prompt=prompt,
        image=img1,
        mask=mask,
        num_resamples=1,
        batch_size=1,
        num_steps=25,
        unconditional_guidance_scale=7.5,
        diffusion_noise=None,
        seed=seed,
        verbose=True,
        )
```

### PR DESCRIPTION
**Pull request by ianstenbit**
@LukeWood

Closes #1019

### CODE REVIEW

**Review by tanzhenyu — APPROVED** [review]

**Comment by tanzhenyu** [comment]
merge without test as this is docstring change

**Comment by BFauber** [comment]
BUG still present in StableDiffusion `inpaint()`. Should I open a new ticket?

Hi @ianstenbit and @tanzhenyu. I can successfully run the SD `inpaint()` function making the mask change @ianstenbit noted where mask = {0,1}, but I have noticed a blurring of the edge where the mask is present. Have you seen this as well?

This blurring is 8 pixels deep, and exists on the left side and top of the image matrix, regardless of the input image. Changing the location of the mask will impact the presence of the blurring, as the blurring will occur only where the mask is present. I cannot create an instance where the blurring is on the right side nor bottom of the image/matrix.

I have not been able to link this blurring bug to any args/parameters of the model, but it looks to be something within the code, possibly the `tf.nn.max_pool2d()` padding step in `inpaint()`.

https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/stable_diffusion/stable_diffusion.py#L333

**Comment by ianstenbit** [comment]
> BUG still present in StableDiffusion `inpaint()`. Should I open a new ticket?
> 
> Hi @ianstenbit and @tanzhenyu. I can successfully run the SD `inpaint()` function making the mask change @ianstenbit noted where mask = {0,1}, but I have noticed a blurring of the edge where the mask is present. Have you seen this as well?
> 
> This blurring is 8 pixels deep, and exists on the left side and top of the image matrix, regardless of the input image. Changing the location of the mask will impact the presence of the blurring, as the blurring will occur only where the mask is present. I cannot create an instance where the blurring is on the right side nor bottom of the image/matrix.
> 
> I have not been able to link this blurring bug to any args/parameters of the model, but it looks to be something within the code, possibly the `tf.nn.max_pool2d()` padding step in `inpaint()`.
> 
> https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/stable_diffusion/stable_diffusion.py#L333

Hey @BFauber sorry for the delay on this. Yes, please open a new ticket for this. I will look into it.

**Comment by BFauber** [comment]
Thanks @ianstenbit for your reply. I have created a new ticket regarding the edge blurring:
https://github.com/keras-team/keras-cv/issues/1158

**Pull request merged**
