### PR TITLE
Add support for PyTorch and Jax to KerasCV

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
# What does this PR do?

This PR adds support for [Keras Core](https://pypi.org/project/keras-core/#description), a new multi-backend implementation for Keras with support for TensorFlow, Jax, and PyTorch. Several backbones and layers have been ported to keras-core along with two object detection models, RetinaNet and YOLOV8.

Backbones ported:

- ResNetV1 (ianstenbit/keras-cv#1)
- ResNetV2 (ianstenbit/keras-cv#2)
- EfficientNetV2 (ianstenbit/keras-cv#2)
- ImageClassifier (ianstenbit/keras-cv#2)
- CSPDarkNet (ianstenbit/keras-cv#4)
- DarkNet (ianstenbit/keras-cv#4)
- MobileNet (ianstenbit/keras-cv#5, ianstenbit/keras-cv#6)
- DenseNet (ianstenbit/keras-cv#7)

Other components ported:

- Object detection layers (ianstenbit/keras-cv#12)
- Preprocessing layers (with TF-only support) (ianstenbit/keras-cv#14, ianstenbit/keras-cv#18)
- Losses (ianstenbit/keras-cv#10)
- Bounding Box utils (ianstenbit/keras-cv#11)
- PyCOCOCallback (ianstenbit/keras-cv#15)

RetinaNet PR: ianstenbit/keras-cv#13
YOLOV8 PR: ianstenbit/keras-cv#8, keras-team/keras-cv#1920

## Who can review?

@ianstenbit @jbischof @fchollet

### CODE REVIEW

**Comment by ianstenbit** [comment]
A note for reviewers -- this code has all already been reviewed via PRs to the `core` branch. Any changes made after this comment have not yet been reviewed. (I suspect we may have to make some changes to make GCB happy)

**Review by mattdangerw — APPROVED** [review]
Looks good!!!

**Review by fchollet — APPROVED** [review]

**Pull request merged**
