### PR TITLE
[Preliminary-PR] Add nms and soft nms to keras-cv

### PR DESCRIPTION
**Pull request by Anirban0011**
What does this PR does:

* This is preliminary PR aimed at adding NMS and Soft-NMS layers to keras-CV. This is no way intended to represent the final implementation. This PR may have conflicts with existing files due to the nature of its implementation. This PR aims to target the basic codeflow that will be used to execute nms and soft-nms layers, if added to keras-cv. 
This PR is **Work-in-Progress** until unless specified.

* With reference from issue #1705 

*  Open for comments

### CODE REVIEW

**Comment by LukeWood** [comment]
Hello @Anirban0011 !  Thank you for your enthusiasm in opening this PR!

a few points of guidance after looking over the PR;
1.) try to solve one issue at a time; NMS or SoftNms (usually start simple)
2.) you layers must be keras layer subclasses
3.) all computation must occur in the TensorFlow graph.  Please check out the TensorFlow docs and familiarize yourself with these concepts
4.) we already have basic NMS, just need soft NMS: https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/object_detection/multi_class_non_max_suppression_test.py

Thanks again for your enthusiasm and good luck ironing these out!

**Comment by Anirban0011** [comment]
@LukeWood , Thanks for your reply. Yeah , I saw that nms implemenation already, I just wrote the nms file for inheriting functions. Alright , I will focus on soft-nms implmentation for now.

**Comment by LukeWood** [comment]
> @LukeWood , Thanks for your reply. Yeah , I saw that nms implemenation already, I just wrote the nms file for inheriting functions to the soft-nms file. Alright anyway, I will focus on soft-nms implmentation for now.

Check out the new comments on the issue!

**Comment by LukeWood** [comment]
Thanks for the heads up on the status!  Lets close this out now that we've gathered some feedback, and have decided to move forward by introducing soft NMS to the original NMS layer!

**Comment by Anirban0011** [comment]
> Thanks for the heads up on the status! Lets close this out now that we've gathered some feedback, and have decided to move forward by introducing soft NMS to the original NMS layer!

Yeah, Thanks. Based on the feedbacks, I should be able to curate a PR by a week or so.

**Pull request closed without merging**
