### PR TITLE
Wrong install documentation string on readme

### PR DESCRIPTION
**Pull request by MrinalTyagi**
# What does this PR do?

Fixed wrong documentation string on readme regarding build from source. 
Fixes (#1268 )
As the wheel that gets built is in format of keras_cv and not keras-cv. 
image

image

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by MrinalTyagi** [comment]
@bhack Feel free to have a look on this

**Review by bhack — APPROVED** [review]

**Review by LukeWood — APPROVED** [review]
Thanks for the bug fix!  @ianstenbit for final approval as he wrote this portion.

**Comment by bhack** [comment]
@LukeWood You could merge. See the filename at https://pypi.org/project/keras-cv/0.4.1/#files

**Review by ianstenbit — APPROVED** [review]
Thanks Mrinal!

**Pull request merged**
