### PR TITLE
Global rename of `classes` to `num_classes`

### LINKED ISSUE #1473: Rename `classes` to `num_classes` throughout KerasCV
For consistency with the KerasNLP API, let's always refer to the number of classes in a classifier, OD model, etc., as `num_classes`. (Currently, `classes` is used in many places)

### PR DESCRIPTION
**Pull request by ianstenbit**
Fixes #1473

### CODE REVIEW

**Comment by ianstenbit** [comment]
#657 👀 

I'll make a PR to KerasIO to update this as well (which we can wait to merge until we cut a release here)

**Review by LukeWood — APPROVED** [review]

**Comment by ianstenbit** [comment]
Corresponding KerasIO change: https://github.com/keras-team/keras-io/pull/1271

**Comment by jbischof** [comment]
Amazing @ianstenbit thank you 🚀 🚀 🚀

**Review by jbischof — APPROVED** [review]

**Pull request merged**
