### PR TITLE
RandomFlip : added test for ragged bounding box

### PR DESCRIPTION
**Pull request by divyashreepathihalli**
issue - https://github.com/keras-team/keras-cv/pull/783

### CODE REVIEW

**Comment by LukeWood** [comment]
Gotcha, so was the error just the missing squeeze?  Thank you Divya for the fix!

**Comment by divyashreepathihalli** [comment]
> Gotcha, so was the error just the missing squeeze? Thank you Divya for the fix!

yes! the squeeze was returning None.

**Review by LukeWood — APPROVED** [review]
Thank you for the fix Divya!

**Pull request merged**
