### PR TITLE
Feature templates

### PR DESCRIPTION
**Pull request by LukeWood**

### CODE REVIEW

**Comment by LukeWood** [comment]
@bhack FYI

**Review by bhack — APPROVED** [review]
I think it is ok. I will eventually restrict this template, using the title/description, to a specific feature subset where mentioning a papers is something plausible (other then more partial/internal feature requests).

**Comment by bhack** [comment]
This will fix https://github.com/keras-team/keras-cv/issues/383 (as it was not connected to this PR).

**Comment by LukeWood** [comment]
Thanks for the review @bhack

**Pull request merged**
