### PR TITLE
Apply sample weight to box regression loss in CenterNet

### PR DESCRIPTION
**Pull request by ianstenbit**
This effectively only computes loss for real boxes, not heatmap entries where no boxes exist in ground truth data.

### CODE REVIEW

**Comment by LukeWood** [comment]
@ianstenbit let me know when this is no longer a WIP

**Comment by ianstenbit** [comment]
> @ianstenbit let me know when this is no longer a WIP

Updated description -- no longer WIP

**Review by LukeWood — APPROVED** [review]
LGTM!

**Pull request merged**
