### PR TITLE
Add black jupyter extension and fix skip tests without custom ops

### PR DESCRIPTION
**Pull request by bhack**
# What does this PR do?
Add black jupiter extension

Fixes https://github.com/keras-team/keras-cv/pull/1149

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by LukeWood — APPROVED** [review]
Thanks!

**Comment by LukeWood** [comment]
@bhack any idea why devcontainer build is failing?

**Comment by bhack** [comment]
> @bhack any idea why devcontainer build is failing?

For custom ops tests. Do we want to run custom ops test in the developer container?

**Comment by LukeWood** [comment]
@bhack please rebase on master, the notebook format is failing but the fix is merged.

**Comment by bhack** [comment]
Someone added new tests with custom ops, in previous PRs, breaking execution without custom ops (since we don't test this configuration in the CI).

**Review by ianstenbit — APPROVED** [review]
LGTM -- thank you!

**Pull request merged**
