### PR TITLE
Revert "(Step 4/5) Add KPLs to RetinaNet training script (#1148)"

### PR DESCRIPTION
**Pull request by tanzhenyu**
The original PR breaks TPU training by introducing ragged tensor

### CODE REVIEW

**Review by ianstenbit — COMMENTED** [review]
Does it make sense to fix-forward here since we do want to switch to the KPLs? Or is that a lot more work?

**Comment by LukeWood** [comment]
For what it’s worth I am re-adding the COCO callback and removing the metrics in the dict box PR.

Fine to proceed either way I will just reintroduce the changes in that PR if that’s easiest

**Comment by tanzhenyu** [comment]
> For what it’s worth I am re-adding the COCO callback and removing the metrics in the dict box PR.
> 
> Fine to proceed either way I will just reintroduce the changes in that PR if that’s easiest

Oh in that case, feel free to go ahead with a forward fix then, I will close this PR

**Review by LukeWood — APPROVED** [review]

**Pull request closed without merging**
