### PR TITLE
Migrate VGG16 from legacy to backbone

### PR DESCRIPTION
**Pull request by pranavvp16**
I have migrated the VGG16 architecture from legacy to backbone in keras_cv. Here is the [notebook](https://colab.research.google.com/drive/11CheIBQZjIuP5p8q410xC6P-ifcnH7f2?usp=sharing) that compares the legacy and migrated model implementation. #2339 .
closes: https://github.com/keras-team/keras-cv/issues/2339

### CODE REVIEW

**Comment by divyashreepathihalli** [comment]
Amazing!! Thanks @pranavvp16 we will take a look!

**Comment by sampathweb** [comment]
@pranavvp16 - Looks like we need to run `bash shell/lint.sh` to sort the imports.  Once its done, the CI should be happy and we can merge the PR.

**Comment by pranavvp16** [comment]
@sampathweb made the changes. The CI should be happy now!

**Comment by sampathweb** [comment]
LGTM. @divyashreepathihalli - I am good to merge.

**Review by divyashreepathihalli — APPROVED** [review]

**Pull request merged**
