### PR TITLE
Vectorize RandomCrop

### PR DESCRIPTION
**Pull request by james77777778**
# What does this PR do?

||Mode|n=100|n=200|n=500|n=1000|
|-|-|-|-|-|-|
|OldRandomCrop|Eager|1.131s|2.286s|5.734s|11.335s|
|OldRandomCrop|Graph|0.052s|0.135s|0.315s|0.605s|
|RandomCrop|Eager|0.007s|0.013s|0.011s|0.015s|
|RandomCrop|Graph|0.002s|0.002s|0.007s|0.009s|

OldRandomCrop is too slow, so I set `n` to `[100, 200, 500, 1000]`

comparison

Visualization:

output

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [X] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?
@LukeWood @ianstenbit

### CODE REVIEW

**Comment by james77777778** [comment]
Some extra notes:

New RandomCrop will get different cropping location for all the images in the same batch unlike the previous OldRandomCrop method.

This PR includes an update that overwrites `_batch_augment` because `augment_bounding_boxes` requires access to the raw images to calculate the differences between input image shape and target image shape. It is not clear if this is a bug in the VectorizedBaseImageAugmentationLayer, as it feeds augmented images directly into `augment_bounding_boxes`, whereas the BaseImageAugmentationLayer behave differently.

https://github.com/keras-team/keras-cv/blob/01e1ffaf38a5db4f3d9f863d11650c00b640fe3e/keras_cv/layers/preprocessing/base_image_augmentation_layer.py#L406-L412

https://github.com/keras-team/keras-cv/blob/01e1ffaf38a5db4f3d9f863d11650c00b640fe3e/keras_cv/layers/preprocessing/base_image_augmentation_layer.py#L451-L462

Old and new RandomCrop do not support batched ragged images as inputs due to implementation constraints that prevent us from obtaining the heights and widths of batched ragged images. The recommended pipeline for working with these images is:

```python
dataset = demo_utils.load_voc_dataset(bounding_box_format="xyxy")
resize = Resizing(
    256, 256, pad_to_aspect_ratio=True, bounding_box_format="xyxy"
)
random_crop = RandomCrop(height=128, width=160, bounding_box_format="xyxy")
dataset = dataset.map(resize, num_parallel_calls=tf.data.AUTOTUNE)
result = dataset.map(random_crop, num_parallel_calls=tf.data.AUTOTUNE)
demo_utils.visualize_data(result, bounding_box_format="xyxy")
```

**Comment by james77777778** [comment]
I will remove the workaround included in this PR once #1594 has been finished.

**Comment by LukeWood** [comment]
@james77777778 merged 1594, so if you can update to remove the workaround we can move forward with this PR!

**Comment by LukeWood** [comment]
Screen Shot 2023-03-28 at 11 15 16 AM

😲 wow - good to fix this :)

**Comment by james77777778** [comment]
Upadeted. Should be good to go.

**Review by LukeWood — APPROVED** [review]
Looks good to me @james77777778 - but one caveat, can you include a sample from the demo in the PR?  Just in a comment is fine!

**Comment by james77777778** [comment]
Hi @LukeWood 
I have already included a same image at the first comment.

https://user-images.githubusercontent.com/20734616/227818953-f19100e8-7017-4564-9f57-57583d0b5be1.png

Do we need more samples? I'm going on vacation. Might be late to reply.

**Comment by LukeWood** [comment]
Thanks @james77777778 !!!

**Pull request merged**
