### PR TITLE
Fix code example in RetinaNet class docstring

### PR DESCRIPTION
**Pull request by DiegoMont**
# Fix code example in RetinaNet class docstring

When running the code as it is currently written in the example (the imports are not in the example), an error is thrown:
```python
images = np.ones((1, 512, 512, 3))
labels = {
    "boxes": [
        [
            [0, 0, 100, 100],
            [100, 100, 200, 200],
            [300, 300, 100, 100],
        ]
    ],
    "classes": [[1, 1, 1]],
}
model = keras_cv.models.RetinaNet(
    num_classes=20,
    bounding_box_format="xywh",
    backbone=keras_cv.models.ResNet50Backbone.from_preset(
        "resnet50_imagenet"
    )
)

# Evaluate model without box decoding and NMS
model(images)

# Prediction with box decoding and NMS
model.predict(images)

# Train model
model.compile(
    classification_loss='focal',
    box_loss='smoothl1',
    optimizer=keras.optimizers.SGD(global_clipnorm=10.0),
    jit_compile=False,
)
model.fit(images, labels)
```
```
ValueError: Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, (<class 'dict'> containing {"<class 'str'>"} keys and {'(<class \'list\'> containing values of types {\'(<class \\\'list\\\'> containing values of types {"<class \\\'int\\\'>"})\'})', '(<class \'list\'> containing values of types {\'(<class \\\'list\\\'> containing values of types {\\\'(<class \\\\\\\'list\\\\\\\'> containing values of types {"<class \\\\\\\'int\\\\\\\'>"})\\\'})\'})'} values)
```

This pull request adds a correction to the `labels` dictionary that fixes the error. I took how the dictionary is created from the definition of the `unpackage_raw_tfds_inputs` function in the **Object Detection with KerasCV** guide from [keras.io](https://keras.io/guides/keras_cv/object_detection_keras_cv/#data-loading)
```python
labels = {
    "boxes": tf.cast([
        [
            [0, 0, 100, 100],
            [100, 100, 200, 200],
            [300, 300, 100, 100],
        ]
    ], dtype=tf.float32),
    "classes": tf.cast([[1, 1, 1]], dtype=tf.float32),
}
```

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by DiegoMont — COMMENTED** [review]
This pull request adds a correction to the labels dictionary that fixes the error. I took how the dictionary is created from the definition of the unpackage_raw_tfds_inputs function in the Object Detection with KerasCV guide from [keras.io](https://keras.io/guides/keras_cv/object_detection_keras_cv/#data-loading)
@ianstenbit @jbischof

**Review by ianstenbit — APPROVED** [review]
Great, thank you for the fix!

**Comment by jbischof** [comment]
@ianstenbit do we want to reintroduce TF code?

**Comment by ianstenbit** [comment]
> @ianstenbit do we want to reintroduce TF code?

I figure for the purpose of a code example this is fine. I thought about using `ops` instead but to new users that might be a bit confusing

**Pull request merged**
