### PR TITLE
Refactor `ResNetV2Backbone` for readability

### LINKED ISSUE #1809: Refactor `ResNetV2Backbone` for readability
Our backbone modeling files are very large and hard to read. @LukeWood proposed two changes in #1745:

1. move aliases to their own file
2. move helpers below model declarations

#1745 provides a nice template for this change for `MobileNetBackbone`. Replicate this change for `keras_cv/models/backbones/resnet_v2/`.

### PR DESCRIPTION
**Pull request by ID6109**
# What does this PR do?

Fixes #1809

### CODE REVIEW

**Review by jbischof — APPROVED** [review]
Looks great thank you!

**Comment by jbischof** [comment]
@ID6109 could you help us with a merge commit?

**Comment by ID6109** [comment]
> @ID6109 could you help us with a merge commit?

Done

**Pull request merged**
