### PR TITLE
Change __new__() args from self to cls

### PR DESCRIPTION
**Pull request by haifeng-jin**
Minor fixes for ResNetV2Backbone.
Changing the `self` to `cls` in `__new__()` signature.

### CODE REVIEW

**Comment by ianstenbit** [comment]
I re-merged from Master to verify that the GCB tests are happy, because as-is they were broken by an existing error.

**Comment by ianstenbit** [comment]
Agh sorry -- it turns out this CI test is broken at head. @LukeWood can you PTAL?

**Comment by ianstenbit** [comment]
Looks like Luke fixed the CI issue in #1558, and it's unrelated.

**Comment by jbischof** [comment]
Thank you @haifeng-jin !

**Pull request merged**
