### PR TITLE
Restructure model tests to try to reduce OOM

### PR DESCRIPTION
**Pull request by ianstenbit**
My opinion is that if these are too slow overall, we might want to consider just making all of the tests under /models run separately as integration tests only.

What are your thoughts? @LukeWood

### CODE REVIEW

**Comment by ianstenbit** [comment]
Tests are all green locally -- let's see what GitHub CI thinks.

**Review by LukeWood — APPROVED** [review]
Certainly not the "right" solution, but at least it unblocks us.

**Comment by LukeWood** [comment]
Thanks @ianstenbit for the fix

**Pull request merged**
