### PR TITLE
Fix patch that somehow got dropped

### PR DESCRIPTION
**Pull request by LukeWood**
Required to work with MixUp(), Mosaic(), and other ragged output layers.

### CODE REVIEW

**Comment by ianstenbit** [comment]
Should this have been caught by a test?

(Also -- looks like you need to run the linter)

**Comment by LukeWood** [comment]
> Should this have been caught by a test?
> 
> (Also -- looks like you need to run the linter)

Honestly its a little hard to repro in a test case, I'd prefer to just fix as a workaround for now - eventually I'd like Mosaic and MixUp to just preserve the last dimension but for now this is the simplest workaround.

**Review by ianstenbit — APPROVED** [review]

**Pull request merged**
