### PR TITLE
Docstring cleanup in randomly_zoomed_crop

### PR DESCRIPTION
**Pull request by soma2000-lang**
#1659
@ianstenbit @haifeng-jin @LukeWood

### CODE REVIEW

**Review by ianstenbit — APPROVED** [review]
Thanks for the PR! 
Looks good to me.

**Comment by ianstenbit** [comment]
@soma2000-lang please fix the code format issue and then we can merge

**Comment by soma2000-lang** [comment]
@ianstenbit Actually I  run the shell/lint.sh,I find the very strange error
image

**Comment by ianstenbit** [comment]
Looks like we're still getting a lint error, this time
```
./keras_cv/layers/preprocessing/randomly_zoomed_crop.py:20:81: E501 line too long (84 > 80 characters)
```

**Comment by soma2000-lang** [comment]
image
@ianstenbit The lint error is due to this

**Comment by LukeWood** [comment]
> image @ianstenbit The lint error is due to this.But this is not related to the changes I have done

ah yeah - we had a change to the linter that is being incrementally done as the issues get caught.  Would you mind reformatting these lines?  80 is our new line length limit!  If not, I'm happy to push a commit

**Comment by soma2000-lang** [comment]
@LukeWood I would be happy to push a commit.There was a problem in my system itself where even adding  # noqa did not help,but have fixed it now.

**Comment by ianstenbit** [comment]
Hey @soma2000-lang it looks like #1676 ended up removing this arg, so I'm going to close this.
Sorry for the signal crossing between contributors. As we get caught up on PR review hopefully we can prevent these duplicate efforts in the future.

We really appreciate your enthusiastic contributions to KerasCV!

**Comment by soma2000-lang** [comment]
@ianstenbit I explicitly mentioned on the issue itself  what prs I am working on.I opened the pr first but the other person's pr got merged earlier which made all my efforts into vain.

**Pull request closed without merging**
