### PR TITLE
Remove the tfds (typo) from the requirements.txt

### PR DESCRIPTION
**Pull request by qlzh727**

### CODE REVIEW

**Comment by ianstenbit** [comment]
We'll still need TFDS in this requirements.txt file -- this was WAI despite the typo because Pip [automagically replaces underscores with dashes](https://pybuilder.io/documentation/publishing-plugins#:~:text=Using%20a%20project%20name%20with,a%20syntax%20error%20at%20import.)

**Comment by qlzh727** [comment]
note that the tfds package already appears in https://github.com/keras-team/keras-cv/blob/8245576207f0cde34f0a1bb502eadf2dbe2a640a/cloudbuild/requirements.txt#L5.

The line I removed is a duplication.

**Comment by ianstenbit** [comment]
> The line I removed is a duplication.

Ack -- thank you, the diff was squashing that.

**Review by ianstenbit — APPROVED** [review]

**Pull request merged**
