### PR TITLE
Add segmask support for random_flip

### PR DESCRIPTION
**Pull request by ianstenbit**
@LukeWood @qlzh727

### CODE REVIEW

**Comment by ianstenbit** [comment]
A handful of KPLs will have a similar pattern to this, where the `augment_segmentation_mask` method will perform either the exact same or a very similar operation on the `segmentation_mask `as the one applied to the `image`.

We could potentially therefore override `augment_segmentation_mask` to simply call `augment_image` with the `segmentation_mask` as a parameter.

The benefit of this is that we'd reduce code duplication, but we'd also make the implementation a bit indirected, and in some cases we may have to update `augment_image` to support the segmask augmentation.

What are your thoughts @LukeWood @qlzh727

**Comment by qlzh727** [comment]
> A handful of KPLs will have a similar pattern to this, where the `augment_segmentation_mask` method will perform either the exact same or a very similar operation on the `segmentation_mask `as the one applied to the `image`.
> 
> We could potentially therefore override `augment_segmentation_mask` to simply call `augment_image` with the `segmentation_mask` as a parameter.
> 
> The benefit of this is that we'd reduce code duplication, but we'd also make the implementation a bit indirected, and in some cases we may have to update `augment_image` to support the segmask augmentation.
> 
> What are your thoughts @LukeWood @qlzh727

SGTM, you can extra a method as `_flip_image` and point both `augment_image` and `augment_segmentation_map` to it. Similarly for other KPLs.

**Review by qlzh727 — CHANGES_REQUESTED** [review]
Please try to extract the image flip into a private method, and make both augment_image and augment_segmentation_map to it.

**Comment by ianstenbit** [comment]
> Please try to extract the image flip into a private method, and make both augment_image and augment_segmentation_map to it.

Done -- thanks!

**Review by qlzh727 — APPROVED** [review]
Thanks.

**Pull request merged**
