### PR TITLE
remove outdated format check

### PR DESCRIPTION
**Pull request by LukeWood**
Testing steps:

- https://colab.sandbox.google.com/github/keras-team/keras-io/blob/master/guides/ipynb/keras_cv/object_detection_keras_cv.ipynb
- change format from xywh -> xyxy
- change format to rel_xywh

Note they all work :)

### CODE REVIEW

**Review by jbischof — APPROVED** [review]
Thank you!

**Review by ianstenbit — APPROVED** [review]
LGTM as long as you've verified that this works fine for other formats.

Thanks @LukeWood!

**Pull request merged**
