### PR TITLE
remove pad_batch_to_shape

### PR DESCRIPTION
**Pull request by LukeWood**

### CODE REVIEW

**Comment by ianstenbit** [comment]
Is this really no longer useful?

What if someone wants to use non-ragged boxes?

**Comment by ianstenbit** [comment]
sg -- please remove other references to this symbol:
https://github.com/keras-team/keras-cv/search?q=pad_batch_to_shape

**Comment by LukeWood** [comment]
> > sg -- please remove other references to this symbol: https://github.com/keras-team/keras-cv/search?q=pad_batch_to_shape
> 
> Done

Somehow my push got dropped, one moment.

**Comment by LukeWood** [comment]
@ianstenbit there we go!

**Review by ianstenbit — APPROVED** [review]

**Pull request merged**
