### PR TITLE
Add some pre-trained weight info to README

### PR DESCRIPTION
**Pull request by ianstenbit**
(Based on conversation in #906)

In the long-term we should provide a nice table of all of our weights' metrics (like Keras Applications), including a ranking system. This is a stop-gap to explain our weights a bit for new users.

### CODE REVIEW

**Comment by bhack** [comment]
Thanks, can we add something about @tanzhenyu comment at https://github.com/keras-team/keras-cv/pull/906#issuecomment-1275388751?

**Review by tanzhenyu — APPROVED** [review]

**Comment by ianstenbit** [comment]
> Thanks, can we add something about @tanzhenyu comment at [#906 (comment)](https://github.com/keras-team/keras-cv/pull/906#issuecomment-1275388751)?

Added a few words about potential difference of preprocessing pipeline.

**Review by bhack — APPROVED** [review]
Ok, let's see what we plan to do next for @tanzhenyu comment:

> ..., reach the paper-claimed result, and then build on top of it. Any difference will bury modeling bugs

**Review by bhack — APPROVED** [review]

**Review by LukeWood — APPROVED** [review]
Looks great!  Thanks for making progress towards the table view

**Comment by bhack** [comment]
Just a reminder for all: We can discuss other things later at https://github.com/keras-team/keras-cv/issues/495

**Pull request merged**
