### PR TITLE
Allow RetinaNet to use exactly 1 class

### PR DESCRIPTION
**Pull request by ianstenbit**
This is no longer a relevant check after #1697

### CODE REVIEW

**Comment by jbischof** [comment]
Should we add testing for the 1 class case?

**Comment by ianstenbit** [comment]
> Should we add testing for the 1 class case?

I'm not really sure what the value would be. The 1 class case isn't really a special case, it's just that softmax doesn't behave nicely with only 1 input. I'm happy to add one though if there's a reason I'm missing.

**Review by jbischof — APPROVED** [review]
OK, just curious if there was some test that would have caught the bug. If not LGTM

**Comment by LukeWood** [comment]
Cool w/ me - should be no issue now

**Pull request merged**
