### PR TITLE
Fix typo in FasterRCNN compile error message

### PR DESCRIPTION
**Pull request by ianstenbit**

### CODE REVIEW

**Comment by bhack** [comment]
Can we add a test on the critical section like in https://github.com/keras-team/keras-cv/pull/1270

**Review by LukeWood — APPROVED** [review]

**Comment by LukeWood** [comment]
LGTM thanks

**Comment by ianstenbit** [comment]
> Can we add a test on the critical section like in #1270

@bhack I'm not sure I follow -- do you mean a test asserting the contents of this error more specifically?

**Comment by bhack** [comment]
I meant the critical section related to the metric. Is it failing under XLA compile?

**Comment by ianstenbit** [comment]
> I meant the critical section related to the metric. Is it failing under XLA compile?

There isn't really a specific metric here to be tested. We're currently disallowing the use of all custom Metrics with OD models due to performance+compatability.

**Pull request merged**
