### PR TITLE
Add pre-trained weights for CSPDarkNet

### PR DESCRIPTION
**Pull request by ianstenbit**
These score 77.44% top-1 accuracy, 98.4% of  [paper-claimed](https://arxiv.org/pdf/2004.10934v1.pdf) result of 78.7

### CODE REVIEW

**Review by LukeWood — APPROVED** [review]

**Comment by LukeWood** [comment]
@quantumalaviya FYI Ian got these trained for you!

**Comment by quantumalaviya** [comment]
Thanks @ianstenbit! These will be very helpful for YoloX.

**Pull request merged**
