### PR TITLE
added fasterRCNN in its own subdirectory

### LINKED ISSUE #1310: Cleanup: move FasterRCNN to its own directory
more complex models probably need subdirectories - alternatively RetinaNet can be flattened in the OD directory.

### PR DESCRIPTION
**Pull request by jaygala223**
Fixes #1310 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [X] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?

Hello @LukeWood and @ianstenbit, can you please review the new PR for
- [ ] #1310

### CODE REVIEW

**Comment by LukeWood** [comment]
Thanks @jaygala223 - looks good to me, lets let tests run!

**Comment by jaygala223** [comment]
Awesome!

**Comment by jaygala223** [comment]
If this works, can I open another Pull Request to flatten RetinaNet in the OD directory as suggested by @LukeWood? (https://github.com/keras-team/keras-cv/issues/1310#issue-1554269170)

**Comment by ianstenbit** [comment]
> If this works, can I open another Pull Request to flatten RetinaNet in the OD directory as suggested by @LukeWood? [#1310 (comment)](https://github.com/keras-team/keras-cv/issues/1310#issue-1554269170)

IIRC @LukeWood had a PR pending for this -- Luke what do you think?

**Comment by jaygala223** [comment]
Thanks, @LukeWood and @ianstenbit for your help and feedback! Looking forward to contributing more and more to KerasCV

**Pull request merged**
