### PR TITLE
Delete .so files

### PR DESCRIPTION
**Pull request by ianstenbit**

### CODE REVIEW

**Review by tanzhenyu — APPROVED** [review]

**Comment by bhack** [comment]
Can you add `.so` file type in https://github.com/keras-team/keras-cv/blob/master/.gitignore ?

**Comment by ianstenbit** [comment]
> Can you add `.so` file type in https://github.com/keras-team/keras-cv/blob/master/.gitignore ?

Good call -- done

**Comment by bhack** [comment]
I suppose the size overhead is small. If not we could remove these from the history with `git filter-branch`.

**Comment by ianstenbit** [comment]
> I suppose the size overhead is small. If not we could remove these from the history with `git filter-branch`.

Total between the two they were 108kb, so I think it's probably not an issue

**Pull request merged**
