### PR TITLE
Rewrite benchmark test for backbones

### PR DESCRIPTION
**Pull request by haifeng-jin**
This is to address [this comment](https://github.com/keras-team/keras-cv/pull/1508/files#r1151189880).
To keep the corresponding PR (#1508) clean since it is an example PR, we will do the rewrite of the test in this separate PR and add the ResNet V1 into the test in that PR (#1508).

### CODE REVIEW

**Comment by haifeng-jin** [comment]
@ianstenbit Would you please provide some guidance on how to get started on this?
I do not know how to run the test.
Thanks

**Comment by ianstenbit** [comment]
> @ianstenbit Would you please provide some guidance on how to get started on this? I do not know how to run the test. Thanks

Awesome!
To run these, you can use 
```
python -i keras_cv/benchmarks/classification_training_benchmark_test.py --benchmarks=benchmark_classification_training_multi_gpu
```

(or `benchmarks=some_other_benchmark_name`), and it will run the relevant test case.
Once it's merged to G3 we can update the internal config to actually run it as a benchmark for regression testing.
 
I'd say we should keep it parameterized by backbone, and in the test case build an `ImageClassifier` with the backbone.

**Comment by haifeng-jin** [comment]
@ianstenbit 
Would you please take a look before I add more backbones?
Making sure it is in the right direction.

Another issue is:
The tests seems finshed, but it prints this error:
```
Traceback (most recent call last):
  File "keras_cv/benchmarks/classification_training_benchmark_test.py", line 108, in <module>
    
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/platform/test.py", line 56, in main
    return _googletest.main(argv)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/platform/googletest.py", line 62, in main
    benchmark.benchmarks_main(true_main=main_wrapper, argv=argv)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/platform/benchmark.py", line 484, in benchmarks_main
    app.run(lambda _: _run_benchmarks(regex), argv=argv)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
SystemExit
```
Do you know if this is normal? or how to fix it?

**Comment by ianstenbit** [comment]
@haifeng-jin with respect to this error, I can't say I've seen this before.

Do you see something like this printed before:
```
entry {
  name: "ClassificationTrainingBenchmark.benchmark_classification_training_multi_gpu__DenseNet121"
  wall_time: 75.67967200279236
  metrics {
    name: "compile_time"
    value: 1.6637299060821533
  }
  metrics {
    name: "avg_epoch_time"
    value: 74.01592898368835
  }
  metrics {
    name: "epochs"
    value: 1.0
  }
  metrics {
    name: "accuracy"
    value: 0.8791000247001648
  }
}
```

When I invoke at head with
```
python3.9 keras_cv/benchmarks/classification_training_benchmark_test.py --benchmarks=benchmark_classification_training_multi_gpu
```
I'm not seeing any such error

**Review by ianstenbit — CHANGES_REQUESTED** [review]
I think the change to the benchmark looks good -- I'm wondering if the error you're seeing is because you're not specifying e.g. `--benchmarks-benchmark_classification_training_multi_gpu` in your invocation?

**Comment by haifeng-jin** [comment]
I tried again. It finished successfully. Last time it was probably running out of memory.

**Review by ianstenbit — APPROVED** [review]
Awesome -- thank you Haifeng!

When Copybara syncs this, we'll break our benchmark tests, but we can fix it forward :)

**Pull request merged**
