### PR TITLE
Typo fixes in converters docs

### PR DESCRIPTION
**Pull request by Anirban0011**
# What this PR does:

* Attempts to fix minor documentation errors in bounding_box/converters.py

### CODE REVIEW

**Comment by Anirban0011** [comment]
@ianstenbit @LukeWood , kindly review . Thanks!

**Comment by ianstenbit** [comment]
Hey @Anirban0011 -- if this double-space-after-period issue is common in the repo, could you fix it across the entire repo in this PR?

**Comment by Anirban0011** [comment]
> Hey @Anirban0011 -- if this double-space-after-period issue is common in the repo, could you fix it across the entire repo in this PR?

Sure I might try to do that, although it could take some time.

**Comment by Anirban0011** [comment]
> > > Hey @Anirban0011 -- if this double-space-after-period issue is common in the repo, could you fix it across the entire repo in this PR?
> > 
> > 
> > Sure I might try to do that, although it could take some time.
> 
> You can probably find and replace ". " with ". " in the repo and sanity check that this doesn't cause any weird issues.

Got it, noted.

**Comment by ID6109** [comment]
@ianstenbit PR #1552 takes care of the double-space issue as well.

**Comment by Anirban0011** [comment]
@ianstenbit due to @ID6109 's PR #1552 being open , In that case we can use this PR to potentially correct few other doc typos other than double spacing, that I thought were off. Should that be fine ?

**Comment by ID6109** [comment]
@Anirban0011 #1552 contains a significant amount of typo fixes as well. So, whatever file(s) you decide to work on next, it would be redundant if the same files are being improved by #1552 . Thanks.

**Comment by Anirban0011** [comment]
> @Anirban0011 #1552 contains a significant amount of typo fixes as well. So, whatever file(s) you decide to work on next, it would be redundant if the same files are being improved by #1552 . Thanks.

@ID6109 , Don't worry, For any future documentation fix , I'll keep a eye on #1552 , so I don't create a conflicting PR, as far as this PR is concerned , I couldn't see any conflicting edits other than that of removal of double spaces. If there any, let me know,. But I think creating a commit reverting to double spaces should make this PR good to to go. Thanks!

**Comment by Anirban0011** [comment]
I have reverted back double space commit due to potential conflict by #1552. @ianstenbit kindly review. Thanks.

**Comment by LukeWood** [comment]
I don't think any of these changes improve the docstring - i.e. the information in the first half of the file is redundant and identical to before this PR, and adding more words reduces conciseness.

Your enthusiasm for improving the docstrings of the package is greatly appreciated, but this one does not seem to improve the state of affairs in a meaningful way!  Keep in mind reviewer time is limited, so if possible I think it would be best to  only send PRs that fix mis-information, rather than just shift wording a bit.

An example of a PR that would be extremely helpful is:

```
boxes: tf.Tensor representing bounding boxes in the format specified in the
            `source` parameter.  `boxes` can optionally have extra dimensions stacked on
             the final axis to store metadata.  boxes should be a 3D Tensor, with the
```

This is actually no longer accurate.  Boxes should be a dictionary now.  No metadata may be passed on the final axis anymore.  Removing that sentence is helpful, but lets steer away from spurious wording changes (i.e. adding `but` or `Here`)

Thanks again for your enthusiasm!  We just need to make sure  we make the best use of reviewer time possible!

**Comment by Anirban0011** [comment]
ok @LukeWood , thnaks for your feedback!

**Pull request closed without merging**
