### PR TITLE
Fix VectorizedBaseImageAugmentationLayer for unbatched bounding_boxes

### LINKED ISSUE #1512: Bug: VectorizedBaseImageAugmentationLayer fails to process unbatched bounding_boxes
I find that current implementation of `VectorizedBaseImageAugmentationLayer` fails to correctly process unbatched `bounding_boxes`

Here is a standalone script:

```python
import tensorflow as tf
from keras_cv.layers import preprocessing

if __name__ == "__main__":
    # construct unbatched input (images, bounding_boxes)
    images = tf.zeros([8, 8, 3])
    bounding_boxes = {
        "boxes": tf.ragged.constant(
            [[0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 1.0, 1.0]],
            dtype=tf.float32,
        ),
        "classes": tf.RaggedTensor.from_tensor(tf.zeros([2, 1])),
    }
    inputs = {"images": images, "bounding_boxes": bounding_boxes}
    # any vectorized layers, take RandomZoom as example
    layer = preprocessing.RandomZoom(0.5, 0.5)
    outputs = layer(inputs, training=True)  # raises ValueError
```

Reason: `VectorizedBaseImageAugmentationLayer` tries to `tf.expand_dims`  (`tf.squeeze`) all values of `inputs` (`outputs`) including `bounding_boxes` which is a dict

https://github.com/keras-team/keras-cv/blob/4fd3a84cb84666644ee52bcc0625f0e4416564dd/keras_cv/layers/preprocessing/vectorized_base_image_augmentation_layer.py#L368-L370

https://github.com/keras-team/keras-cv/blob/4fd3a84cb84666644ee52bcc0625f0e4416564dd/keras_cv/layers/preprocessing/vectorized_base_image_augmentation_layer.py#L392-L394

The possible solution:

```python
            # _format_inputs
            for key in list(inputs.keys()):
                if key == BOUNDING_BOXES:
                    inputs[BOUNDING_BOXES]["boxes"] = tf.expand_dims(
                        inputs[BOUNDING_BOXES]["boxes"], axis=0
                    )
                    inputs[BOUNDING_BOXES]["classes"] = tf.expand_dims(
                        inputs[BOUNDING_BOXES]["classes"], axis=0
                    )
                else:
                    inputs[key] = tf.expand_dims(inputs[key], axis=0)
                ...
            # _format_output
            for key in list(output.keys()):
                if key == BOUNDING_BOXES:
                    output[BOUNDING_BOXES]["boxes"] = tf.squeeze(
                        output[BOUNDING_BOXES]["boxes"], axis=0
                    )
                    output[BOUNDING_BOXES]["classes"] = tf.squeeze(
                        output[BOUNDING_BOXES]["classes"], axis=0
                    )
                else:
                    output[key] = tf.squeeze(output[key], axis=0)
```

It needs to be fixed if we want to implement `augment_bounding_boxes` for vectorized layers.

I can open the PR once approved.

### PR DESCRIPTION
**Pull request by james77777778**
# What does this PR do?

Fixes #1512 

I add an unit test `test_augment_unbatched_all_data` and try to fix some bugs in the original test:

- No assertion

https://github.com/keras-team/keras-cv/blob/cd12204b1f6df37b15359b6adf222b9ef0f67dc8/keras_cv/layers/preprocessing/vectorized_base_image_augmentation_layer_test.py#L123-L128

- Redundant variable assignment

https://github.com/keras-team/keras-cv/blob/cd12204b1f6df37b15359b6adf222b9ef0f67dc8/keras_cv/layers/preprocessing/vectorized_base_image_augmentation_layer_test.py#L254

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [X] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?
@LukeWood @ianstenbit

### CODE REVIEW

**Comment by james77777778** [comment]
Kindly ping @LukeWood @ianstenbit 

Without this fix, unit tests might fail when we vectorize KPL with bbox support.

**Review by LukeWood — APPROVED** [review]
Thanks @james77777778 !  I really appreciate the extra effort you put into making all of your PRs high quality.

**Comment by james77777778** [comment]
Kindly ping @LukeWood @ianstenbit 
Once this PR merged, I can begin to vectorize KPLs supporting bbox augmentation.

P.S.
I really like the vectorizing design of KPLs in KerasCV and that is why I devote myself to it. It is fast, powerful and easy to use.
From my past experiences, it is hard to write performant pipeline for TF/Keras without a lot of survey and googling...
KerasCV could be a very good demonstration of preprocessing for TF/Keras. Thanks again for this great work!

**Comment by LukeWood** [comment]
@james77777778 thanks - I just rebased lets see if the tests pass.

**Comment by LukeWood** [comment]
Thanks @james77777778

**Pull request merged**
