### PR TITLE
Make contrastive API private

### PR DESCRIPTION
**Pull request by ianstenbit**
As requested by @tanzhenyu (since API has not been formally approved yet)

@tanzhenyu @fchollet PTAL at the contrastive learning design doc so that we can finalize this API and make it public in KerasCV

@LukeWood

### CODE REVIEW

**Comment by LukeWood** [comment]
What is the motivation to make this private?  Isn't the API finalized?

**Review by tanzhenyu — APPROVED** [review]

**Comment by ianstenbit** [comment]
> What is the motivation to make this private? Are there outstanding API changes? Ideally I’d like to have a tutorial for this launched by mid October.

@tanzhenyu are you able to take a look at the design for this? I am going to merge this and make this private for now, but this will be important for Luke's conference talk so we should make sure we have a path forward to make this public.

**Comment by tanzhenyu** [comment]
> > What is the motivation to make this private? Are there outstanding API changes? Ideally I’d like to have a tutorial for this launched by mid October.
> 
> @tanzhenyu are you able to take a look at the design for this? I am going to merge this and make this private for now, but this will be important for Luke's conference talk so we should make sure we have a path forward to make this public.

Approved. Closing this PR.

**Pull request closed without merging**
