### PR TITLE
[Draft] Addition of Yolo v7

### PR DESCRIPTION
**Pull request by MrinalTyagi**
# What does this PR do?

Addition of YoloV7 model. (Draft PR)
Related to issue: #1179 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP is used?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by quantumalaviya** [comment]
Nice! Some observations that may be transferable from my implementation of YoloX: 

1. This should follow the KerasCV Object Detection API, you can check out the existing RetinaNet implementation for that. Personally, this took the longest time other than the implementation of the head. You will need to separate the backbones, FPNs, heads, encoder, decoder, etc. This gives the model a lot more flexibility.
2. Training scripts and tests are missing.
3. I see that you added a draft PR in the description so the last point may be invalid but you might want to update this to a draft PR status.
4. Following the structure of RetinaNet makes more sense.

Correct me if I misinterpreted anything! I just had a quick look at the structure and the code.

**Comment by MrinalTyagi** [comment]
@quantumalaviya Thanks a lot for your valuable feedback. I was a bit confused about the implementation section for the same and just gave a draft implementation. But after looking at your wip of YOLOX, I got to know how to structure the code and separate different components. Will try to implement the same here.

**Comment by MrinalTyagi** [comment]
> Thanks for the PR @MrinalTyagi - this is a ton of code and I'm really glad to see this written.
> 
> We'll need to do this in a series of many PRs instead of one big PR. Please break this into PRs
> 
> my recommendation is to do the following steps:
> 
> * create one layer at a time per PR, please include unit tests
> * create YOLOv7 after creating all layers

Sure @LukeWood I will follow the specified path. Is it fine that I first complete the whole work in this pr and then split it into multiple prs? By that way I feel would be more comfortable for me specially in this case

**Comment by MrinalTyagi** [comment]
@quantumalaviya Can you please have a look at the yolov7_backbone.py file? I have tried to incorporate some of the changes insisted by you to separate the backbone and head differently.

**Comment by LukeWood** [comment]
> Sure @LukeWood I will follow the specified path. Is it fine that I first complete the whole work in this pr and then split it into multiple prs? By that way I feel would be more comfortable for me specially in this case

Of course!  Please include [draft] in the title until you’re ready.

**Comment by MrinalTyagi** [comment]
Sorry for the delay on this. I was a bit busy with my end-term examinations. I have tried to basically make a backbone and club different backbones used into breakable code in the most separable fashion.  Would it be possible to provide your valuable feedback on the structure of the file 'yolov7_backbone.py'? @quantumalaviya @LukeWood 
After this, I plan on working on the other structures of the model after this is approved from your end of regarding the rough implementation structure. I am side by side working on adding the unit tests as well as documentation for all layers.

**Comment by LukeWood** [comment]
We now have YOLOv8 from @ianstenbit 's PR and it looks this PR has been inactive for quite some time.  Closing for now, but feel free to check out the YOLOv8 implementation for inspiration if you ever want to take another stab at this.

**Pull request closed without merging**
