### PR TITLE
Remove Augmenter usage in README

### PR DESCRIPTION
**Pull request by haifeng-jin**
Related to #1548

### CODE REVIEW

**Comment by LukeWood** [comment]
@haifeng-jin do you know what TensorFlow this bumps our minimal dependency to?

**Comment by LukeWood** [comment]
> @LukeWood I don't know. I don't think it would change the minimal TF version. The sequantial model should support KPLs all the time, right?

Actually this is why the augmenter class exists.  Previously the Sequential model would error out when using KPLs with dictionary formatted inputs.  I believe it might be 2.12 minimum to support, perhaps 2.11 - no matter the case lets make sure to bump the minimum version so we don't confuse users.

**Review by ianstenbit — APPROVED** [review]
Thanks!

I'm honestly surprised this doesn't show up in any of our other examples / codebase, but I suppose that's a good thing!

@LukeWood do you want to verify the TF version dependency before merging?

**Pull request merged**
