### PR TITLE
Fix typos in base_image_augmentation_layer docs

### PR DESCRIPTION
**Pull request by Anirban0011**
What this PR does:

* Fixes minor docstring issues in layers/preprocessing/base_image_augmentation_layer.py

### CODE REVIEW

**Comment by Anirban0011** [comment]
#1533

**Comment by Anirban0011** [comment]
#1541

**Comment by Anirban0011** [comment]
#1544

**Comment by Anirban0011** [comment]
#1545

**Comment by Anirban0011** [comment]
@ianstenbit @LukeWood , please have a look at the doc fix.Thanks

**Review by ianstenbit — APPROVED** [review]
Looks good -- thanks

**Comment by Anirban0011** [comment]
Thanks for the PR approval!

**Pull request merged**
