### PR TITLE
Explicitly specify full package for more modules, as shown in #2001

### LINKED ISSUE #2070: keras_cv 0.6.3 fails on import due to conflicting "load" functions
### Current Behavior:
After fresh install of keras_cv and tensorflow, keras_cv fails to import in Python 3.11 on Mac OS. (High Sierra 10.13.6)

### Expected Behavior:
Expected a successful importing of keras_cv module.

### Steps To Reproduce:
Create a new conda environment `conda create --name test python=3.11`
Activate the environment `conda activate test`
Install tensorflow  dependencies `conda install -c apple tensorflow`
Install keras_cv `pip install keras-cv tensorflow --upgrade`
Enter python `python`
Attempt to import keras_cv `import keras_cv`
See error:
```
Using TensorFlow backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/__init__.py", line 11, in <module>
    from keras_cv import datasets
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/datasets/__init__.py", line 8, in <module>
    from keras_cv.datasets import imagenet
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/datasets/imagenet/__init__.py", line 8, in <module>
    from keras_cv.src.datasets.imagenet.load import load
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/src/datasets/imagenet/__init__.py", line 14, in <module>
    from keras_cv.src.datasets.imagenet.load import load
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/src/datasets/imagenet/load.py", line 59, in <module>
    @keras_cv_export("keras_cv.datasets.imagenet.load")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/src/api_export.py", line 38, in __call__
    maybe_register_serializable(symbol, self.package)
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras_cv/src/api_export.py", line 27, in maybe_register_serializable
    keras.saving.register_keras_serializable(package=package)(symbol)
  File "//miniconda3/envs/test/lib/python3.11/site-packages/keras/saving/object_registration.py", line 154, in decorator
    raise ValueError(
ValueError: keras_cv>load has already been registered to <function load at 0x1471296c0>
```
### Version:
Pip 23.2.1
Tensorflow 2.12.0
Keras-cv 0.6.3

Any help is appreciated.

### PR DESCRIPTION
**Pull request by BjarneHerland**
Explicitly specify full package-name for several methods upon registering as serialisable. 

Fixes #2070

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

### CODE REVIEW

**Review by ianstenbit — APPROVED** [review]
Thank you for this fix!

**Comment by ianstenbit** [comment]
Hi @BjarneHerland  -- please take a look at the linter error

```
./keras_cv/datasets/imagenet/load.py:60:17: E128 continuation line under-indented for visual indent
./keras_cv/datasets/pascal_voc/segmentation.py:46[9](https://github.com/keras-team/keras-cv/actions/runs/6199600190/job/16905705278?pr=2077#step:8:10):17: E128 continuation line under-indented for visual indent
./keras_cv/keypoint/converters.py:64:17: E128 continuation line under-indented for visual indent
```

Thanks again for the fix!

**Comment by jbischof** [comment]
Thanks @BjarneHerland. What behavior does this change?

**Comment by BjarneHerland** [comment]
> Thanks @BjarneHerland. What behavior does this change?

No problem 👍  It resolves the issue seen in https://github.com/keras-team/keras-cv/issues/2070 by following the lead from https://github.com/keras-team/keras-cv/pull/2001

On a clean checkout master without this fix, running e.g.

`python -c "import keras_cv"`

bombs out with naming collisions. (It puzzles me why registration is done like this though, but https://github.com/keras-team/keras-cv/pull/2001 was accepted, so I follow... 🤷  We could probably fix `maybe_register_serializable()` to extract and use the package-part from `symbol`, with some fallback if necessary, to avoid specifying the package explicit for lots of modules.)

**Comment by BjarneHerland** [comment]
> On a clean checkout master without this fix, running e.g.
> 
> `python -c "import keras_cv"`
> 
> bombs out with naming collisions

Something seems to have changed recently (improved lazy-loading?) but this import still triggers the issue for me

`python -c "import keras_cv.datasets.imagenet"`

**Comment by ianstenbit** [comment]
Looks like we've still got some linter errors:
```
./keras_cv/datasets/load_test.py:21:9: F401 'keras_cv.datasets' imported but unused
./keras_cv/datasets/load_test.py:24:[9](https://github.com/keras-team/keras-cv/actions/runs/6247561832/job/17046212537?pr=2077#step:8:10): F401 'keras_cv.datasets.imagenet' imported but unused
./keras_cv/datasets/load_test.py:28:5: F821 undefined name 'tf'
```

You can run the linter locally by running `sh shell/lint.sh` from the base directory of the `keras_cv` repo 😀

**Comment by BjarneHerland** [comment]
> You can run the linter locally by running `sh shell/lint.sh` from the base directory of the `keras_cv` repo 😀

Yeah - forgot to do that for the test 😒  Sorry!

**Pull request merged**
