### PR TITLE
Switch to one-configuration-per-architecture GCB testing for backbones

### PR DESCRIPTION
**Pull request by ianstenbit**
This dramatically cuts down on model testing time while still keeping good coverage of backbones. WDYT?

### CODE REVIEW

**Review by tanzhenyu — COMMENTED** [review]
Would this mean that we have to manually test those commented models if relevant changes are made?

**Comment by ianstenbit** [comment]
> Would this mean that we have to manually test those commented models if relevant changes are made?

More or less, yes. This would mean that when a backbone is updated we need to manually run its tests if we want to check every configuration of the model. Given the infrequency with which we update backbones, I think this is reasonable. 

The backbones will _still be tested_ by CI, just not _every_ configuration of every backbone, which is arguably overkill even when changes are made to the implementation.

**Review by tanzhenyu — APPROVED** [review]
LGTM! Thanks for fixing it temporarily!

**Pull request merged**
