### PR TITLE
Makes MLPMixer a Functional subclass model & removes closures

### LINKED ISSUE #1426: Make MLPMixer a Functional subclass model & remove closures
This should follow the example of #1412 and #1401, including

- Docstring updates
- Colab demonstrating that weight loading works (if pre-trained weights exist) and numerics are identical

### PR DESCRIPTION
**Pull request by ID6109**
# What does this PR do?

Fixes #1426 

[Colab](https://colab.research.google.com/drive/1hVNFinBMXZMGGB3MEHeN0fXSn4JD66FY?usp=sharing)

## Who can review?
@LukeWood @ianstenbit @tanzhenyu

### CODE REVIEW

**Review by ianstenbit — APPROVED** [review]
Thanks for the PR!
Looks good

**Comment by ianstenbit** [comment]
@ID6109 please take a look at the formatting issue

**Comment by ID6109** [comment]
Updated

**Comment by ianstenbit** [comment]
CI failure is unrelated and fixed by #1517

**Pull request merged**
