### PR TITLE
Fixed dropblock 2d serialization issue.

### LINKED ISSUE #343: Fix Dropblock2d's serialization issue.
Two things:

1. I noticed recently most preprocessing layers have been decorated with:  
`@tf.keras.utils.register_keras_serializable(package="keras_cv")`  
this could also be added to DropBlock I think.

2. When attempting to deserialize a model with this layer, one will encounter error, most likely **kwargs are missing from init.
```python
import tensorflow as tf
from keras_cv.layers.regularization.dropblock_2d import DropBlock2D

model = tf.keras.Sequential([DropBlock2D(0.1, 7)])
model.build(input_shape=(224, 224, 3))
tf.keras.models.save_model(model, "model.h5")
with tf.keras.utils.custom_object_scope({"DropBlock2D": DropBlock2D}):
    loaded = tf.keras.models.load_model("model.h5")
```

`TypeError: __init__() got an unexpected keyword argument 'trainable'`

If you give a green light for these changes I'd be happy to submit a PR.

### PR DESCRIPTION
**Pull request by sebastian-sz**
Fixes #343

### CODE REVIEW

**Comment by LukeWood** [comment]
Hey Sebastian!  Thanks for the commit.  Looks great overall!

2 minor things:

1.). you can remove the name parameter here as you mentioned; I feel comfortable approving that with no discussion
2.). See https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/serialization_test.py

for the serialization test.  Thanks!!!

**Comment by sebastian-sz** [comment]
@LukeWood thanks!
1. Removed explicit `name` parameter.
2. Rewrote the test to be like the one in `serialization_test.py`.

Let me know if this is ok!

**Comment by LukeWood** [comment]
Thanks @sebastian-sz - dropped force_generator=True (faster to make one liner changes myself than leave a comment - so often times I'll do that)

Thanks for the PR and bug report.  As always, a pleasure receiving your PRs

**Comment by sebastian-sz** [comment]
@LukeWood thanks, glad it worked out!

Btw, why did you remove `force_generator=True`? As far as I remember:
* True makes use of `tf.random.Generator`
* False makes use of deprecated `tf.random` API

Right now running `test_works_with_xla` will raise warning:
```
2022-04-23 12:06:17.315417: W tensorflow/compiler/tf2xla/kernels/random_ops.cc:57] 
Warning: Using tf.random.uniform with XLA compilation will ignore seeds; 
consider using tf.random.stateless_uniform instead if reproducible behavior is desired. 
drop_block2d/random_uniform/RandomUniform
```

What's the current policy regarding `tf.random` API? Is Generator or are stateless ops prefferred?

**Comment by LukeWood** [comment]
> @LukeWood thanks, glad it worked out!
> 
> Btw, why did you remove `force_generator=True`? As far as I remember:
> 
> * True makes use of `tf.random.Generator`
> * False makes use of deprecated `tf.random` API
> 
> Right now running `test_works_with_xla` will raise warning:
> 
> ```
> 2022-04-23 12:06:17.315417: W tensorflow/compiler/tf2xla/kernels/random_ops.cc:57] 
> Warning: Using tf.random.uniform with XLA compilation will ignore seeds; 
> consider using tf.random.stateless_uniform instead if reproducible behavior is desired. 
> drop_block2d/random_uniform/RandomUniform
> ```
> 
> What's the current policy regarding `tf.random` API? Is Generator or are stateless ops prefferred?

I did this to match the rest of the augmentation layers.   We could force it to all of them, but I'd like it all to be consistent.

**Pull request merged**
