### PR TITLE
Test out migrating to tensorflow from tf-nightly

### PR DESCRIPTION
**Pull request by LukeWood**

### CODE REVIEW

**Comment by LukeWood** [comment]
Should work on 2.9

**Comment by bhack** [comment]
Can we close this as we have https://github.com/keras-team/keras-cv/commit/e2a8874e8b875de1cc8b335961bf766da93cadf9 in master?

**Comment by LukeWood** [comment]
> Can we close this as we have [e2a8874](https://github.com/keras-team/keras-cv/commit/e2a8874e8b875de1cc8b335961bf766da93cadf9) in master?

I'd like to drop the check when 2.9 is out and just rely on `tensorflow` again.

**Comment by LukeWood** [comment]
I guess we can close it, may as well.

**Pull request closed without merging**
