### PR TITLE
add reduction=none parameter to losses to fix retinanet detection example

### LINKED ISSUE #795: RetinaNet example losses error
I got the following error, when I run the object detection example:
```ValueError: RetinaNet expects the output shape of `classification_loss` to be `(batch_size, num_anchor_boxes)`.  Expected classification_loss(predictions)=(None, None), got classification_loss(predictions)=(). Try passing `reduction='none'` to your classification_loss's constructor.```
Similar one is raised for box loss.

### PR DESCRIPTION
**Pull request by akucia**
# What does this PR do?
Fixes #795 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?
@LukeWood

### CODE REVIEW

**Comment by ianstenbit** [comment]
Thank you for the PR!

This LGTM but I want to verify with @LukeWood that this is correct.

Also -- @akucia please take a look at the message from the google-cla bot

**Comment by akucia** [comment]
Thanks, CLA should be fixed now.

**Comment by LukeWood** [comment]
Thanks for the PR!

**Comment by LukeWood** [comment]
Hey @akucia !  Can you run shell/format.sh and update the results here to make linting pass?

**Comment by LukeWood** [comment]
Thank you for the PR @akucia !!!  its good to keep the examples running!

**Pull request merged**
