### PR TITLE
Add performance benchmarking scripts for COCO Metrics

### PR DESCRIPTION
**Pull request by LukeWood**

### CODE REVIEW

**Comment by LukeWood** [comment]
This could be a useful example for our users if they want to benchmark other metrics/components.

**Comment by bhack** [comment]
Do we have the CI ready to test notebooks?

**Comment by bhack** [comment]
If understand correctly this will let us to have just to get the final texecution time but any insight like  Tensorflow profiler about the ops, timeline etc.
Can we add [profiler directives](https://www.tensorflow.org/api_docs/python/tf/profiler/experimental/start)?

If I remember correctly it requires a base model to fulfill stats.

**Comment by bhack** [comment]
> If I remember correctly it requires a base model to fulfill stats.

P.s. probably the Keras model isn't strictly required if we use  https://www.tensorflow.org/api_docs/python/tf/profiler/experimental/Trace

**Comment by bhack** [comment]
Some Tensorflow and Google repos are using:

https://www.reviewnb.com/

**Comment by LukeWood** [comment]
I'd rather avoid using a non-github tool to review PRs.  I'll migrate these to scripts.  There's no real reason for these to not be scripts anyways - just an artifact of how I developed these.

**Comment by bhack** [comment]
My proposal:

- I think that we could use just the plain python code as a regular test
- We could add a [performance custom markers](https://docs.pytest.org/en/6.2.x/example/markers.html#mark-examples) so that we could enable/filter this in the CI as we like
- We could use `tf.profiler` like I've done in this [dummy example](https://colab.research.google.com/gist/bhack/36b6900d49a62487778fbaab3e2082dc/trace_profiler.ipynb)

**Comment by LukeWood** [comment]
@fchollet re-formatted as scripts.

**Comment by LukeWood** [comment]
FYI @qlzh727 as well

**Pull request merged**
