### PR TITLE
Whitelisted format and linting files and folders for bash scripts

### LINKED ISSUE #386: `shell/lint.sh` fails with exit code 1 without giving proper error
Following the issue discussed in [#104](https://github.com/keras-team/keras-nlp/issues/104) for Keras-NLP (which is now resolved), there is a need for whitelisting directories and files which are needed to be linted and formatted, avoiding virtual environment directory.

### PR DESCRIPTION
**Pull request by adhadse**
Resolves #386.
Now I have whitelisted files and folders that are specifically needed for linting and formatting. 
Hey @LukeWood, This PR is ready for review!!!

### CODE REVIEW

**Comment by LukeWood** [comment]
Thanks for the PR. 

Any benefit to doing this instead of just running `black .`?

**Comment by adhadse** [comment]
The problem has to do with virtual environment folder that often user creates in the project repo. This leads to formatting and linting performed on code which is not of our concern. 

This eliminates that problem, making our scripts robust.

**Comment by LukeWood** [comment]
Can we exclude the problematic venv dir instead?

**Comment by adhadse** [comment]
The problem is there is nothing really canonical there for a name, the directory could be anything. I tried to do the same, and I realized it was wrong. That's why this [PR](https://github.com/keras-team/keras-nlp/pull/105#pullrequestreview-938483411) was closed for good

**Comment by LukeWood** [comment]
Thanks for the PR @adhadse.  I'd rather actually lint the entire repo.  We will continue adding more directoires over time, and as such I'd like to ensure we enforce lint and format checks for any new directories.

I would recommend placing your venv somewhere outside of the repo.  I think this is probably the best, low-tech solution.

**Pull request closed without merging**
