### PR TITLE
Migrate VGG16 to subclass `Backbone`

### LINKED ISSUE #1630: Migrate VGG16 to the new `Backbone` API
To align KerasCV with the KerasNLP API, we're migrating our backbone models to subclass keras_cv.models.Backbone.
This allows us to have a more structured, modular API for high-level task models, including the new ImageClassifier model (see https://github.com/keras-team/keras-cv/pull/1458).

A great step-by-step guide to this migration can be found in the description of https://github.com/keras-team/keras-cv/pull/1508, which performed this migration for ResNetV1.

If you'd like to take this issue up, please leave a comment and the KerasCV team can assign the issue to you. When opening a PR, please tag this issue as fixed by your PR, and tag our tracking bug https://github.com/keras-team/keras-cv/issues/1627 for bookkeeping.

### PR DESCRIPTION
**Pull request by ID6109**
# What does this PR do?

Fixes #1630 

## Who can review?
@ianstenbit @jbischof

### CODE REVIEW

**Comment by ID6109** [comment]
@ianstenbit @LukeWood can you please confirm if we need a preset file here in the first place?

**Comment by ID6109** [comment]
> @ianstenbit @LukeWood can you please confirm if we need a preset file here in the first place?

@ianstenbit @jbischof Should I make a `VGGBackbone` with `vgg16` and `vgg19` as presets?

**Comment by ID6109** [comment]
> @ianstenbit @LukeWood can you please confirm if we need a preset file here in the first place?

@ianstenbit @jbischof Should I make a `VGGBackbone` with `vgg16` and `vgg19` as presets?

**Comment by jbischof** [comment]
I don't think we want to move forward with this model as it is no longer relevant. Apologies @ID6109!

**Pull request closed without merging**
