### PR TITLE
Implement check to skip value range transform

### PR DESCRIPTION
**Pull request by LukeWood**

### CODE REVIEW

**Review by qlzh727 — APPROVED** [review]
Probably add a simple test case, just for coverage.

**Comment by LukeWood** [comment]
> Probably add a simple test case, just for coverage.

Yeah, I was wondering about that.  Any suggestion @qlzh727?  We’d have to inspect the graph, right?

**Comment by bhack** [comment]
@qlzh727 How is this working between the preprocessing layers chain?

Are we going to have some important casting overhead as we have profiled at:
https://github.com/keras-team/keras-cv/issues/165#issuecomment-1061225089

**Comment by qlzh727** [comment]
if the value range for all the image are (0, 255) for the input image, then it will benefit from this change (since it skip the conversion). When the input range are (0, 1), then any chain of the layer will keep converting them between (0, 1) and (0, 255). We might want to add some warning to user if this method has been hit several times in the pipeline, and suggest user to pre-convert their value to (0, 255). 

Anyway, this method is always good to have since it always skip the unnecessary conversion.

**Comment by bhack** [comment]
> We might want to add some warning to user if this method has been hit several times in the pipeline, and suggest user to pre-convert their value to (0, 255).

Can we find a way to communicate/propagate between KLP layers that the range is converted?

**Comment by bhack** [comment]
As I suppose that a chain of transformation is a quite common use case and it could be the O() of the casting overhead.

**Pull request merged**
