### PR TITLE
Restructure StableDiffusion namespace and folder hierarchy

### PR DESCRIPTION
**Pull request by ianstenbit**
Also adds a note to the SD docstring about API instability.

### CODE REVIEW

**Comment by LukeWood** [comment]
Looks great!  just to confirm, did you run SD weight loading based on this PR?  just as a sanity check all the symbol moves are working as expected.

**Comment by ianstenbit** [comment]
> Looks great! just to confirm, did you run SD weight loading based on this PR? just as a sanity check all the symbol moves are working as expected.

I ran the tests which do perform weight loading. Since I managed to introduce a bug on accident with my last PR, I'm also going to run my music video generator script before I merge

**Review by LukeWood — APPROVED** [review]
LGTM

**Pull request merged**
