### PR TITLE
Fix typos in cut_mix docs

### PR DESCRIPTION
**Pull request by Anirban0011**
# What this PR does :

* Fixes minor doc issues in layers/preprocessing/cut-mix.py

### CODE REVIEW

**Comment by Anirban0011** [comment]
@ianstenbit  have a look at these doc fixes! Thanks!

**Comment by Anirban0011** [comment]
Thanks for approving the PR changes @LukeWood , kindly have a review of my other pending PRs for similar kind of docs fixes. Thanks!

**Comment by Anirban0011** [comment]
@LukeWood @ianstenbit kindly merge if possible. Thanks!

**Comment by ianstenbit** [comment]
Merged from Master to fix broken CI

**Review by ianstenbit — APPROVED** [review]
LGTM - thanks!

**Comment by ianstenbit** [comment]
@Anirban0011 thank you for your enthusiasm in sending these typo fixes!

If you plan to send more fixes in the future, could you please batch a group of them into a single PR instead of sending many separate PRs?
Having lots of separate PRs, each with their own comments, can create noise which makes it harder to track and review all of the open changes.

Thank you!

**Comment by Anirban0011** [comment]
> @Anirban0011 thank you for your enthusiasm in sending these typo fixes!
> 
> If you plan to send more fixes in the future, could you please batch a group of them into a single PR instead of sending many separate PRs? Having lots of separate PRs, each with their own comments, can create noise which makes it harder to track and review all of the open changes.
> 
> Thank you!

Tanks for your suggestions. I'll keep it in mind while doing a PR next time. Thanks!

**Pull request merged**
