### PR TITLE
Format weight conversion script

### PR DESCRIPTION
**Pull request by LukeWood**
just ran:

```
./shell/format.sh
```

with the jupyter extension installed

Right now every time I run ./shell/format.sh on any branch this gets formatted, so lets update to prevent it from showing up in future PRs.

### CODE REVIEW

**Comment by ianstenbit** [comment]
@LukeWood is there a change to our CI that would have prevented this from getting merged in the first place?
Otherwise LGTM

**Comment by bhack** [comment]
https://github.com/keras-team/keras-cv/blob/fc2c6154b8b83060d9d2f761812ffacc0b001f08/.github/workflows/actions.yml#L71

But I don't see the black notebook plugin required:
https://github.com/keras-team/keras-cv/blob/fc2c6154b8b83060d9d2f761812ffacc0b001f08/setup.py#L49-L56

**Comment by bhack** [comment]
Check this PR https://github.com/keras-team/keras-cv/pull/1150

**Review by tanzhenyu — APPROVED** [review]

**Comment by bhack** [comment]
https://github.com/keras-team/keras-cv/actions/runs/3707967243/jobs/6285008631

**Pull request merged**
